### ISSUE TITLE
Enable regex operations

### ISSUE THREAD

**Issue by ckitsanelis** [TNO/vscode-tracy#19]
- [ ] define conditions based on regexes, with flag/state values determined by capture groups
- [x] search & filter using Boolean operations (not, and, or), and regexes

**Comment by dennisrd** [comment]
A few suggestions for the extension with regexes:
The list of available operations (contains, equals, startsWith, endsWith) that can be used to construct conditions is extended with the operation "matches regex". In the field Text, the user then specifies a regex. Assume JavaScript syntax for the regex, but without surrounding quotes or forward slashes. For example, the regex `Client\d` is used to match any string "Client0", ..., "Client9". (In JavaScript, one would use the constructor `new RegExp('Client\d')` or the literal `/Client\d/`.)
The regex may contain capturing groups. The annotation (i.e. the flag or state) being defined may refer to the matches using JavaScript backreference notation (`\1`, `\2`, ...). For example, the regex is `Client(\d)` and the annotation being defined is `CLIENT_NUMBER_\1`.

**Comment by dennisrd** [comment]
With regex matching, the other operations (contains, equals, startsWith, endsWith) can be defined. I suggest to leave them for convenience. It would also be convenient to have "notEquals" as an additional operation.

**Comment by dennisrd** [comment]
A proposal:

As for extending the search & filter feature with Boolean operations and regexes, a check box is added to indicate whether the search string is to be interpreted either as [text, possibly with Boolean operators] or as [a regex].

For the Boolean operators, we pick the ones from JavaScript (`&&`, `||`, and `!`) or just `AND`, `OR`, and `NOT`. Assuming the latter ones for now, the precedence order is NOT, AND, OR. The literals that these operators apply to are strings without whitespace. So `NOT Error` finds all strings that do not contain the substring `Error`. Parentheses are used to create strings that include whitespace, and to create more complex Boolean expressions. For example, `((client connect) AND Success) OR NOT Error` finds all strings that contain _both_ the substring `client connect` (with a single space) _and_ the substring `Success`, as well as all strings that do not contain the substring `Error`. Other occurrences of whitespace are meaningless, so searching for `client connect` (without parentheses) should not be allowed: the user must be explicit about whether they mean `(client connect)`, `client AND connect`, or `client OR connect` (or something else).

**Comment by dennisrd** [comment]
> A proposal:

Some modifications to the above proposal after talking to a few people about their preferences:

1.  Searching for `work document` searches for the words `work` and `document` in the same text; the same search is performed by `work AND document`. To search for the exact phrase  `work document`, use  `"work document"`. In addition, `OR` and `NOT` can be used, as well as parentheses to group expressions. To include the characters `"`, `(`, `)` in the search string, escape them with a backslash: `\"`, `\(`, `\)`.
2.  Add a toggle for case sensitive search.

**Comment by ckitsanelis** [comment]
Operations with regular expressions, flags with capture groups and robust search options have been added.
I suggest to close this issue

**Comment by dennisrd** [comment]
I'll close it.
Just for the record: A feature request that remains is to be able to use regex captures in the definition of state machines, for state tracking annotations.
