### ISSUE TITLE
Usability improvements

### ISSUE THREAD

**Issue by lunalixxi** [TNO/vscode-tracy#2]
- [x] column resizing
- [x] color the cells (background color) of the log text using the same colors that are used in the corresponding cells in the minimap; it should be possible to switch this on or off
- [x] hide/show columns in the minimap
- [ ] #15

**Comment by dennisrd** [comment]
Hi Luna. I suggest to combine the 2nd and 3rd items: the idea would be to color the cells (background color) of the log text using the same colors that are used in the corresponding cells in the minimap. It should be possible to switch this on or off.
This feature has low priority.

**Comment by dennisrd** [comment]
PS. I merged the items and also added another one

**Comment by NuukPrime** [comment]
Since the only item on the list of THIS issue already has its own issue (namely issue: #15) ... maybe THIS issue can be closed?

**Comment by lunalixxi** [comment]
> Since the only item on the list of THIS issue already has its own issue (namely issue: #15) ... maybe THIS issue can be closed?

yes, it can be closed.
