### ISSUE TITLE
Flag annotations

### ISSUE THREAD

**Issue by dennisrd** [TNO/vscode-tracy#5]
Another type of annotation column that the user should be able to add, besides state-based annotations, are flags. Using flags, events can be annotated when they satisfy certain user-specified conditions. The mechanism is quite similar to state-based annotations. The values that occur in a flag column are called flags (instead of states). The conditions that specify whether a certain flag marks an event are similar to the conditions that specify state transitions in case of a state-based annotation. A difference is that, in contrast to a state, a flag marks an individual event and does not "persist" to the next event.

**Comment by ckitsanelis** [comment]
Included in v0.0.6
